---
    pid_file : /var/zenoh-flow/registry.pid
    path : /etc/zenoh-flow/registry
    chunks_dir : /var/zenoh-flow/registry/chunks
    is_local: true,
    zenoh :
      kind: client
      listen: ["tcp/127.0.0.1:35997"]
      locators: ["unixsock-stream//var/zenoh-flow/registry/local.sock"]