[package]
name = "cargo-zenoh-flow"
version = "0.1.0"
repository = "https://github.com/eclipse-zenoh/zenoh-flow"
homepage = "http://zenoh.io"
authors = ["kydos <angelo@icorsaro.net>",
           "gabrik <gabriele.baldoni@gmail.com>",
           "Julien Loudet <julien.loudet@adlinktech.com>",]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]
description = "Zenoh-Flow: zenoh-based data-flow programming framework for computations that span from the cloud to the device."
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "=1.9.0", features = ["attributes"] }
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "master", optional = true}
zenoh-util = { git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "master", optional = true }
zenoh-flow = {path = "../zenoh-flow"}
structopt = "0.3"
clap = "2.33"
serde_derive = "1.0"
serde = { version = "1.0", features = ["derive"] }
cargo_toml = "0.10"
toml = "0.5.8"
serde_yaml = {version = "0.8"}
serde_json = "1.0"
rand = { version = "0.8", optional =  true}
tinytemplate = "1.2"
colored = "2"
log = "0.4"

[[bin]]
name = "cargo-zenoh-flow"
path = "src/bin/main.rs"


[lib]
path = "src/lib.rs"

[features]

local_registry = ["zenoh","zenoh-util", "rand"]

default = ["local_registry"]